#' Extract data from ODK Collect instance XMLs (without ODK Briefcase)
#'
#' Reads all submission XMLs stored under an ODK Collect `instances/`
#' directory and returns them as a named list of data frames (one per
#' repeat level). It does NOT use ODK Briefcase, so it works even when
#' Briefcase is too old to parse the form (e.g. Briefcase 1.18 vs.
#' forms generated by pyxform >= 3).
#'
#' Each submission is expected to live in its own subfolder of
#' `instancesDir`, e.g. `instances/treeCensusForm_2026-10-06_16-38-57/`.xml`.
#' Repeats are detected automatically by looking for `jr:template`
#' elements in the first instance.
#'
#' @param instancesDir Path to the ODK Collect `instances` directory.
#' @param expDir Optional. If provided, each data frame is also written
#'   as a CSV in this directory. Naming follows ODK Briefcase:
#'   `<formBase>.csv` for the main form and `<formBase>-<repeat>.csv`
#'   for each repeat (nested repeats use `-` as separator, e.g.
#'   `<formBase>-subquad-tree-sec_stem.csv`).
#' @param formBase Base name for the output CSVs. If NULL, derives from
#'   the first instance XML found.
#' @param overwrite Logical. If FALSE (default), existing CSVs are not
#'   overwritten.
#' @param mediaOutDir Optional. If provided, all non-XML files found in
#'   the instance folders (photos, etc.) are copied here, preserving
#'   the subfolder structure.
#'
#' @return Invisibly, a named list of data frames. Names are `""`
#'   (main form) plus each repeat path (e.g. `"subquad"`,
#'   `"subquad/tree"`, ...). Columns use dot-separated paths for nested
#'   groups, exactly as in Briefcase CSV exports.
#' @author Alexandre Adalardo de Oliveira \email{aleadalardo@gmail.com}
#' @seealso
#' \url{http://labtrop.ib.usp.br}
#' @references \url{https://opendatakit.org/}
#' @examples
#' \dontrun{
#' dfs <- readInstancesXML("inst/testDataODK/instances",
#'                         expDir = "inst/exportDataODK/testDataODK",
#'                         formBase = "treeCensusForm")
#' }
#' @export
readInstancesXML <- function(instancesDir,
                             expDir = NULL,
                             formBase = NULL,
                             overwrite = FALSE,
                             mediaOutDir = NULL) {
  if (!requireNamespace("xml2", quietly = TRUE)) {
    stop("Package 'xml2' is required.")
  }
  if (!dir.exists(instancesDir)) {
    stop("Directory not found: ", instancesDir)
  }

  ## 1. Find instance XMLs
  xmls <- list.files(instancesDir, pattern = "\\.xml$",
                     recursive = TRUE, full.names = TRUE)
  if (length(xmls) == 0) {
    stop("No instance XML found in: ", instancesDir)
  }

  if (is.null(formBase)) {
    formBase <- sub("\\.xml$", "", basename(xmls[1]))
  }

  ## 2. Detect repeat paths from the first instance
  doc0 <- xml2::read_xml(xmls[1])
  repeatPaths <- .detectRepeatPaths(doc0)
  message("Repeat paths detected: ",
          paste(c("<root>", repeatPaths), collapse = ", "))
  message("Processing ", length(xmls), " instance file(s)...")

  ## 3. Prepare accumulator: named list by repeat path
  allRecords <- list()
  allRecords[[""]] <- list()
  for (p in repeatPaths) allRecords[[p]] <- list()

  ## 4. Walk each instance
  nOk <- 0L
  nFail <- 0L
  for (xp in xmls) {
    ok <- tryCatch({
      doc <- xml2::read_xml(xp)
      root <- xml2::xml_find_first(doc, "/*[local-name()='data']")
      if (is.na(root)) stop("No <data> root element.")

      instID <- xml2::xml_text(xml2::xml_find_first(root, "./meta/instanceID"))
      instID <- trimws(instID)
      if (!nzchar(instID)) {
        instID <- paste0("uuid:", sub("\\.xml$", "", basename(xp)))
      }

      .walkRecord(root,
                  thisKey      = instID,
                  parentKey    = "",
                  depthPath    = "",
                  allRecords   = allRecords,
                  repeatPaths  = repeatPaths)
      TRUE
    }, error = function(e) {
      warning("Skipping ", xp, ": ", conditionMessage(e))
      FALSE
    })
    if (isTRUE(ok)) nOk <- nOk + 1L else nFail <- nFail + 1L
  }
  message("Instances parsed OK: ", nOk, "; failed: ", nFail)

  ## 5. Convert to data frames
  dfs <- lapply(allRecords, function(lst) {
    if (length(lst) == 0) return(data.frame())
    allCols <- unique(unlist(lapply(lst, names)))
    mat <- matrix("",
                  nrow = length(lst),
                  ncol = length(allCols),
                  dimnames = list(NULL, allCols))
    for (i in seq_along(lst)) {
      row <- lst[[i]]
      for (nm in names(row)) {
        mat[i, nm] <- row[[nm]]
      }
    }
    as.data.frame(mat, stringsAsFactors = FALSE)
  })

  ## 6. Optionally save CSVs
  if (!is.null(expDir)) {
    if (!dir.exists(expDir)) {
      dir.create(expDir, recursive = TRUE)
    }
    for (nm in names(dfs)) {
      suffix <- if (nzchar(nm)) paste0("-", gsub("/", "-", nm)) else ""
      fname  <- file.path(expDir, paste0(formBase, suffix, ".csv"))
      if (file.exists(fname) && !overwrite) {
        warning("File exists, skipping: ", fname)
        next
      }
      utils::write.csv(dfs[[nm]], fname, row.names = FALSE, na = "")
      message("Wrote ", nrow(dfs[[nm]]), " row(s) to ", fname)
    }
  }

  ## 7. Optionally copy media files
  if (!is.null(mediaOutDir)) {
    if (!dir.exists(mediaOutDir)) {
      dir.create(mediaOutDir, recursive = TRUE)
    }
    allFiles  <- list.files(instancesDir, recursive = TRUE, full.names = TRUE)
    isFile    <- !dir.exists(allFiles)
    notXml    <- !grepl("\\.xml$", allFiles, ignore.case = TRUE)
    mediaFiles <- allFiles[isFile & notXml]
    if (length(mediaFiles) > 0) {
      rootNorm <- normalizePath(instancesDir, winslash = "/", mustWork = FALSE)
      for (f in mediaFiles) {
        fNorm <- normalizePath(f, winslash = "/", mustWork = FALSE)
        rel   <- sub(paste0("^", rootNorm, "/?"), "", fNorm)
        dest  <- file.path(mediaOutDir, rel)
        dir.create(dirname(dest), recursive = TRUE, showWarnings = FALSE)
        file.copy(f, dest, overwrite = FALSE)
      }
      message("Copied ", length(mediaFiles), " media file(s) to ", mediaOutDir)
    } else {
      message("No media files found in ", instancesDir)
    }
  }

  invisible(dfs)
}


#' Detect repeat paths in an ODK instance XML
#'
#' A repeat is identified by the presence of an element carrying a
#' `jr:template` attribute (pyxform always writes one). The function
#' returns the dot/slash-notated path of each such element relative to
#' the `<data>` root.
#'
#' @param doc An `xml2` document (a single ODK instance).
#' @return A character vector of repeat paths, e.g. `c("subquad",
#'   "subquad/tree", "subquad/tree/sec_stem", "subquad/rep_miss",
#'   "subquad/rep_miss/sec_stem_miss")`.
#' @keywords internal
.detectRepeatPaths <- function(doc) {
  all_elems <- xml2::xml_find_all(doc, "//*")
  paths <- character(0)
  for (n in all_elems) {
    a <- xml2::xml_attrs(n)
    is_tpl <- any(names(a) == "template" | grepl(":template$", names(a)))
    if (!is_tpl) next
    p <- xml2::xml_path(n)
    p <- sub("^/data/?", "", p)
    if (nzchar(p)) paths <- c(paths, p)
  }
  unique(paths)
}


#' Walk one record of an ODK instance and register it (plus any repeats)
#'
#' @param node The XML element representing the record.
#' @param thisKey The KEY assigned to this record.
#' @param parentKey The KEY of the parent record ("" for the root).
#' @param depthPath The repeat path of this record ("" for the root).
#' @param allRecords Accumulator: named list of lists of named character
#'   vectors (one entry per record).
#' @param repeatPaths Character vector of all repeat paths in the form.
#' @return Invisibly NULL. Mutates `allRecords`.
#' @keywords internal
.walkRecord <- function(node, thisKey, parentKey, depthPath,
                        allRecords, repeatPaths) {
  ## 1. Direct repeat child names for this record
  directRepeats <- character(0)
  for (rp in repeatPaths) {
    parts  <- strsplit(rp, "/", fixed = TRUE)[[1]]
    parent <- if (length(parts) > 1) paste(head(parts, -1), collapse = "/") else ""
    if (parent == depthPath) {
      directRepeats <- c(directRepeats, parts[length(parts)])
    }
  }
  directRepeats <- unique(directRepeats)

  ## 2. Collect leaf values (skipping direct repeat children)
  rec <- .collectLeafValues(node, stopNames = directRepeats)
  rec["KEY"] <- thisKey
  if (nzchar(parentKey)) rec["PARENT_KEY"] <- parentKey

  ## 3. Register this record
  allRecords[[depthPath]][[length(allRecords[[depthPath]]) + 1L]] <- rec

  ## 4. Recurse into direct repeat children
  if (length(directRepeats) > 0) {
    kids   <- xml2::xml_children(node)
    knames <- xml2::xml_name(kids)
    for (rn in directRepeats) {
      matches <- kids[knames == rn]
      if (length(matches) == 0) next
      keep <- vapply(matches, function(k) {
        a <- xml2::xml_attrs(k)
        !any(names(a) == "template" | grepl(":template$", names(a)))
      }, logical(1))
      matches <- matches[keep]
      childPath <- if (nzchar(depthPath)) paste0(depthPath, "/", rn) else rn
      for (i in seq_along(matches)) {
        childKey <- paste0(thisKey, "/", rn, "[", i, "]")
        .walkRecord(matches[[i]],
                    thisKey     = childKey,
                    parentKey   = thisKey,
                    depthPath   = childPath,
                    allRecords  = allRecords,
                    repeatPaths = repeatPaths)
      }
    }
  }
  invisible(NULL)
}


#' Collect leaf values (dot-separated paths) under an XML element
#'
#' Recurses through the tree, producing a named character vector where
#' names are dot-separated paths (e.g. `"parcela.quadrat"`). Elements
#' whose name is in `stopNames` are not entered (they are repeats,
#' handled by `.walkRecord`).
#'
#' @param node The XML element (a record).
#' @param stopNames Names to skip (direct repeat children).
#' @param prefix Prefix for nested paths (internal use).
#' @return A named character vector.
#' @keywords internal
.collectLeafValues <- function(node, stopNames = character(), prefix = "") {
  out <- character(0)
  kids <- xml2::xml_children(node)
  for (k in kids) {
    nm <- xml2::xml_name(k)
    if (nm %in% stopNames) next
    full  <- if (nzchar(prefix)) paste0(prefix, ".", nm) else nm
    grand <- xml2::xml_children(k)
    if (length(grand) == 0) {
      val <- xml2::xml_text(k)
      out[full] <- if (is.na(val)) "" else val
    } else {
      sub <- .collectLeafValues(k, stopNames = stopNames, prefix = full)
      out <- c(out, sub)
    }
  }
  out
}
