#' Convert XLSForm to ODK XML using pyxform
#'
#' This function converts an Excel XLSForm (.xlsx) into an ODK-compliant XML file
#' using the Python library \code{pyxform} bundled within the R package.
#' It also performs a basic integrity check on the generated XML file.
#'
#' @param xlsxPath Character. Path to the input Excel (.xlsx) file.
#' @param xmlPath Character. Path where the output XML file should be saved.
#'   If NULL, it will be saved in the same directory with a .xml extension.
#' @param briefcase118 Logical. If \code{TRUE} (default), the generated XML is
#'   post-processed to be compatible with ODK Briefcase 1.18.0, which embeds
#'   an older JavaRosa parser that ignores (and in practice rejects) the
#'   attributes \code{odk:xforms-version}, \code{orx:max-pixels} and
#'   \code{max-pixels}, as well as decimal form versions such as
#'   \code{"20261006.01"}. The original XML is preserved as \code{<xmlPath>.orig}.
#'
#' @return Character. The path to the generated XML file, invisibly.
#' @export
#'
#' @examples
#' \dontrun{
#' xmlForm("data/treeCensusForm.xlsx", "data/treeCensusForm.xml")
#' }
xmlForm <- function(xlsxPath, xmlPath = NULL, briefcase118 = TRUE) {
    # 1. Setup python pyxform environment
    setupPyEnv()
  # 2. Validate input file existence
  if (!file.exists(xlsxPath)) {
    stop("The specified Excel file does not exist: ", xlsxPath)
  }

  # Define default output path if not provided
  if (is.null(xmlPath)) {
    xmlPath <- sub("\\.xlsx$", ".xml", xlsxPath, ignore.case = TRUE)
  }

  # 4. Import pyxform modules locally
  tryCatch({
    pyxformXls2json <- reticulate::import("pyxform.xls2json")
    pyxformBuilder <- reticulate::import("pyxform.builder")
  }, error = function(e) {
    stop("Could not import 'pyxform' from the bundled package directory. Error: ", e$message)
  })

  message("Converting ", xlsxPath, " to XML...")

  # 5. Run conversion using pyxform
  tryCatch({
    # Parse XLS to intermediate JSON structure
    surveyJson <- pyxformXls2json$parse_file_to_json(xlsxPath)
    
    # Create Survey element from dictionary
    survey <- pyxformBuilder$create_survey_element_from_dict(surveyJson)
    
    # Write XForm XML to file
    survey$print_xform_to_file(xmlPath)
    message("XML successfully generated at: ", xmlPath)
  }, error = function(e) {
    stop("Error during pyxform conversion: ", e$message)
  })

  # 5b. Post-processing: ODK Briefcase 1.18 compatibility
  if (isTRUE(briefcase118)) {
    .makeBriefcase118Compatible(xmlPath)
  }

  # 6. Verify XML integrity and return problems if any
  if (file.exists(xmlPath)) {
    if (requireNamespace("xml2", quietly = TRUE)) {
      tryCatch({
        # Attempt to read the XML to check if it is well-formed
        xmlDoc <- xml2::read_xml(xmlPath)
        message("Integrity check: XML is valid and well-formed.")
      }, error = function(e) {
        warning("XML was generated but failed integrity validation: ", e$message)
      })
    } else {
      message("Install the 'xml2' package to enable advanced XML integrity validation.")
    }
  } else {
    stop("XML file was not found after the conversion process.")
  }

  return(invisible(xmlPath))
}


#' Make an XForm generated by pyxform >= 3 compatible with ODK Briefcase 1.18.0
#'
#' ODK Briefcase 1.18.0 embeds an old JavaRosa parser that does not recognize
#' attributes introduced by recent pyxform versions
#' (\code{odk:xforms-version}, \code{orx:max-pixels} / \code{max-pixels}) nor
#' decimal form versions such as \code{"20261006.01"}. When it finds those
#' constructs during the \code{pull_collect}, Briefcase silently discards the
#' form, leaving the storage empty; subsequent \code{--export} then fails with
#' \code{"Form <id> not found"}.
#'
#' This helper rewrites the XML in place, stripping those constructs:
#' \itemize{
#'   \item removes the \code{odk:xforms-version} attribute from \code{<model>};
#'   \item removes \code{orx:max-pixels} and \code{max-pixels} attributes;
#'   \item normalizes \code{version="YYYYMMDD.NN"} to \code{version="1"}.
#' }
#' The original file is backed up as \code{<xmlPath>.orig} (only once).
#'
#' @param xmlPath Character. Path to the XForm XML file to be adjusted.
#'
#' @return Invisibly returns \code{TRUE} if the file was modified,
#'   \code{FALSE} otherwise.
#' @keywords internal
.makeBriefcase118Compatible <- function(xmlPath) {
  if (!file.exists(xmlPath)) {
    warning("XML file not found for post-processing: ", xmlPath)
    return(invisible(FALSE))
  }

  txt  <- readLines(xmlPath, warn = FALSE)
  orig <- txt

  # 1) remove 'odk:xforms-version' attribute from <model>
  txt <- gsub(' odk:xforms-version="[^"]*"', "", txt)

  # 2) remove 'orx:max-pixels' and plain 'max-pixels' attributes
  txt <- gsub(' orx:max-pixels="[^"]*"', "", txt)
  txt <- gsub(' max-pixels="[^"]*"',     "", txt)

  # 3) normalize version="YYYYMMDD.NN" -> version="1"
  #    (only applied to the 'version' attribute, which in a standard
  #     pyxform-generated XForm appears just once, on <data>)
  txt <- gsub('version="[0-9]+\\.[0-9]+"', 'version="1"', txt)

  if (identical(txt, orig)) {
    message("Briefcase 1.18 compatibility: nothing to adjust in XML.")
    return(invisible(FALSE))
  }

  backup <- paste0(xmlPath, ".orig")
  if (!file.exists(backup)) {
    writeLines(orig, backup)
  }
  writeLines(txt, xmlPath)

  message("Briefcase 1.18 compatibility: XML adjusted.")
  message("  - 'odk:xforms-version' attribute removed from <model>")
  message("  - 'max-pixels' / 'orx:max-pixels' attributes removed")
  message("  - 'version=\"..\"' normalized to an integer value")
  message("  - backup of original file: ", backup)

  invisible(TRUE)
}


setupPyEnv <- function() {
  pkg_name <- "odkTreeCensus"
# 1. Tenta o caminho de desenvolvimento (pasta local do projeto)
  dev_path <- file.path("inst", "python")
  
  # 2. Se a pasta local 'inst/python' existir (modo dev), usa ela. 
  # Caso contrário, usa o caminho padrão do pacote instalado.
  if (dir.exists(dev_path)) {
    wheels_dir <- dev_path
  } else {
    wheels_dir <- system.file("python", package = pkg_name)
  }

  # Validação simples
  if (wheels_dir == "" || !dir.exists(wheels_dir)) {
    stop("Erro: A pasta 'inst/python' (dev) ou 'python' (instalado) não foi encontrada.")
  }

  # Caminho para salvar o virtualenv no cache do usuário
  venv_path <- file.path(tools::R_user_dir(pkg_name, "cache"), "python_env")

  # Instalação offline caso o ambiente Python não exista no cache
  if (!reticulate::virtualenv_exists(envname = venv_path)) {
    message("Criando ambiente Python offline...")
    reticulate::virtualenv_create(envname = venv_path)
    
    wheels <- list.files(wheels_dir, pattern = "\\.whl$", full.names = TRUE)
    
    if (length(wheels) == 0) {
      stop(paste("Nenhum arquivo .whl encontrado em:", wheels_dir))
    }
    
    # Instala os wheels sem usar a internet
    reticulate::py_install(
      packages = wheels,
      envname = venv_path,
      pip_options = c("--no-index", paste0("--find-links=", wheels_dir))
    )
  }

  # Ativa o virtualenv na sessão
  reticulate::use_virtualenv(virtualenv = venv_path, required = TRUE)
}
